# Generated by Django 3.2.16 on 2023-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("course", "num")},
        ),
        migrations.AlterField(
            model_name="news",
            name="preamble",
            field=models.CharField(max_length=1024, verbose_name="preamble"),
        ),
    ]
